### ISSUE TITLE
installation fails 

### ISSUE THREAD

**Issue by lemna** [giabaio/survHE#1]
Hi, 

installation using devtools fails:

> devtools::install_github("giabaio/survHE")
Error: Line starting '<<<<<<< HEAD ...' is malformed!

This is with the latest github version of devtools:

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.2.1           R6_2.2.0             tools_3.3.2          withr_1.0.2          curl_2.2            
 [6] memoise_1.0.0        knitr_1.15.1         git2r_0.16.0         digest_0.6.10        devtools_1.12.0.9000

Any suggestions?

Thanks
Peter.

**Comment by giabaio** [comment]
OK --- not sure what's going on. I *think* this may have to do with encoding, possibly of the DESCRIPTION file. I'll investigate further and try and sort this out asap! The package installs successfully under Linux --- I'll check under Mac OS too. I think somebody else has managed to install it in Windows. I'll try and check that too.

**Comment by giabaio** [comment]
Peter,
Can you please try again now? I think the DESCRIPTION file got accidentally
tampered with and there was some extra text, which shouldn't have...

Please let me know if now it works!
Gianluca



*Gianluca Baio*

*Reader in Statistics & Health Economics*
Department of Statistical Science
University College London
1-19 Torrington Place, London WC1E 6BT, UK
Telephone +44(0)20 7679 1248 (internal: 41248)
Fax +44 (0)20 7383 4703
Website: http://www.homepages.ucl.ac.uk/~ucakgba
<http://www.homepages.ucl.ac.uk/~ucakgba/>
Blog: http://gianlubaio.blogspot.co.uk

**Comment by lemna** [comment]
Yes, it works now. I managed to install it and run <example(fit.models)> successfully. 

You might want to list multcomp, polspline and SparseM as dependencies - I can file a PR if you'd like.

Thanks for fixing!
Peter.

**Comment by giabaio** [comment]
Thanks Peter --- glad it works now! Let me know if you find any other issue... 
As for the other dependencies, yes please!

G
