### ISSUE TITLE
create development branch?

### ISSUE THREAD

**Issue by lemna** [giabaio/survHE#13]
Hi Gianluca,

the windows build is failing on the master branch. I'm wondering: wouldn't it be better to have a development branch to work on, in addition to a master branch that will provide a functioning version for users to install?

Peter.

**Comment by giabaio** [comment]
Hi Peter,
Yes --- I have seen this. There's a new version of `INLA`, which some changes that break `survHE`. I think I know how to fix them (and I think the newer version has passed the Travis test already). I was fixing it, but then got stuck with meetings etc... :-(

Will try to fix it all later. But you do make a valid point --- just need to time to set these up!

**Comment by lemna** [comment]
It's possible that the first failure is actually related to the travis setup. Have you seen this: http://stackoverflow.com/questions/32361567/java-lang-unsatisfiedlinkerror-gomp-4-0-travis-ci-using-java-opencv-library? This suggest that a change to travis.yml could fix it, rather than adding dynload.workaround() to the R code. If it works there is no need to introduce a new warning for using `:::`.

**Comment by giabaio** [comment]
OK --- thanks. This seems to have fixed the issue with Travis. The Windows build is also OK. I still haven't created the package webpage, where I plan on putting the stable version of the build (both .tar.gz and .zip), but will do asap.
