### ISSUE TITLE
Roadmap - future development

### ISSUE THREAD

**Issue by giabaio** [giabaio/survHE#15]
So, in case people are interested, these are the future development that I would like to implement/bring in the next versions of `survHE` (in *no* particular order of priority or importance!)

1. Extend all HMC versions of the models currently implemented to allow a more general version in which the ancillary parameters (as well as the location parameters) can depend on covariates. This is not terribly difficult in principle - but may also not be super-relevant, particularly in the context of health economic evaluation, as models are usually constructed by assuming that the ancillary parameters do not depend on the observed covariates.
2. Implement more flexible models, eg those in [Murray et al](http://www.biostat.umn.edu/~brad/software/Revision_BA1407-004.pdf). Again, it's not super complicated to construct HMC-based versions of these models. I don't think they've been used much in health economic evaluation, mostly, I think, because practitioners do not know them/their possible advantages.
3. Expand the INLA-based versions of the models currently supported. This may be a big deal - `INLA` does work pretty well on the range of models it does support currently and it can expand the impact of Bayesian analysis in health economic evaluations based on survival data. It would be nice (and particularly relevant!) to also implement the RPS models in `INLA`.
4. Speaking of, expand the RPS capabilities of `survHE` to include the other versions (proportional odds + probit). `flexsurv` already does these, but `survHE` implementation doesn't.
5. This also may be a biggie - it's about expanding the facilities of `survHE` in terms of digitised data. I think [Andrea](https://github.com/andbe) did have some ideas/comments/code to apply.
6. And related to this, what would also be very helpful to practitioners, I think, would be to have some reporting facilities (along the lines of [BCEAweb](https://egon.stats.ucl.ac.uk/projects/BCEAweb/) or [bmetaweb](https://egon.stats.ucl.ac.uk/projects/bmetaweb/)). This way, the user could make all the analysis with `survHE` and then have some sort of standardised report, which could form the basis of the output to send to clients or submit to agencies (eg NICE). Possibly this would fit well with a web-app version of `survHE`?
7. Expand Will's work on testing the assumptions behind each parametric model. At the moment, this is kind of developed for a few models, but needs a bit more work in terms of expanding and clarifying the objectives/output, as well as in terms of generalising to more distributions.
8. Possibly the most important, follow even more closely NICE's guideline on survival analysis in health economic evaluation and see if there's anything else that is currently missing (eg in terms of structures such as partitioned models).

Lots of work, then and potentially some of this could either be under/post-graduate projects, or even be embedded in funded work... More food for thoughts...

**Comment by lemna** [comment]
Hi Gianluca, 

A couple of thoughts, for what it's worth...
- features 1-4 are all about additional models. It would be awesome to have some kind of plugin mechanism, or at least a formal specification of how additional models should be implemented (which functions need to be updated, expected input/output,...).
- write a vignette showing how to perform a complete analysis and report on it according to NICE guidelines, using either `knitr` or `ReporteRs`. Show required plots and tables, which assumptions need to be checked, how to select models, etc. This could be used as a kind of template for real analyses.
- Most companies won't allow employees to submit data to a third-party website. Any web application that is not hosted internally is very unlikely to be used for proprietary data. I'd rather focus on the kind of sample report above.
- boring stuff, but important for use in production:
-- documentation needs to be up to date. Consider switching to Roxygen to ensure that documentation is accurate.
-- error handling: ensure that appropriate warnings and errors are thrown if inappropriate input is given. At the moment a number of functions allow to pass inappropriate input to `...`, which is then silently ignored. The user needs to be made aware when this happens. 
-- consistent plotting: it's necessary to follow client or internal style guidelines and SOPs. I personally like the flexibility that ggplot2 offers. For example, I use themes to make all plots conform to company style.
-- reporting: ensure that reporting output from summary and print functions can be integrated with tabulating packages, such as `htmlTable` and `xtable`. Also, ensure that the package plays nice with `knitr` and `ReporteRs`. Word and PowerPoint integration is very important for most organizations.
-- add unit tests, to ensure that functions result in the expected results.
-- add a development branch and set up some sort of timeline for release of the master branch to CRAN. In other words, what is needed before you release? Could you list missing features etc. in the github issue list?

with kind regards
Peter

**Comment by giabaio** [comment]
In terms of 1-4, there's an important distinction to be made, I think. As for the changes to `INLA`, we (I) need to liase with the `INLA` developers (which I am already) and much of the changes are kind of external to `survHE`, ie we can suggest and make sure that `survHE` complies with newer versions of `INLA`. For the additional models to be developed under HMC, we can be independent on the `rstan` development, in the sense that *all* (I say all...) is needed is a bunch of new model files (eg implementing different survival models), or changes to the existing `.stan` files to include new/different features. (In fact, in addition to this, I need to recompile the whole set of models, so they can run straightaway from `survHE`). In many ways, this is a more technical and methodological bit, as it is important to know what we want to do and what model(s) we want to implement...

As for the reporting, you are right about the sensitivity issue with data. *But*: you can create a local version of the webapp (eg a `survHEweb` package that you install on your machine) and then launch it locally - you would then operate `survHE` from the graphical interface and all would happen locally, with no necessity of sharing data... Like with `BCEAweb` and `bmetaweb`, I don't think that the graphical interface supersedes directly the command line package, but it can be useful in some (many?) cases...

Related to this, a vignette with a worked case study is most certainly on the table and I would like to find the time to actually do this. In fact it'd be nice to follow through with a worked "real" example. Will did so in his thesis and perhaps we could use part of what he's done... But it'd be also helpful, I think, to have an automatic report-capability. I see your point about customising the way it looks (with company headers etc); but of course, this is something that the user can do separately? And I think `knitr` for example does allow you to customise the template of the resulting document (and also, I don't expect many users to go with `LaTeX`, unfortunately...).

Finally, we're already discussing this off line - it's helpful to have Roxygen-style documentation, I agree. As for the development version, I kind of see the GitHub version as the beta release, especially now that I have managed (thanks for the pointers as well!) to create the local repository and installing the stable version of `survHE` is relatively easy... Submission to CRAN is also a possibility, of course.

**Comment by lemna** [comment]
- What I'd be interested in is to use custom models in survHE. We implement these in `flexsurv` at the moment - so it would be nice if there were some written guidelines on how to "plug" these into `survHE`. 
- Regarding the worked case study, a number of journals accept tutorial articles (I've actually done two based on my thesis). A publication might be an incentive to work on it?
- I don't think the package needs extensive reporting capabilities, just ensure that users can integrate it easily in their existing workflow. I agree that layout and styling is the user's responsibility. What I mean is, for example, the mixture of both `ggplot` and traditional graphics at the moment makes it harder to achieve consistent graphics layout. Strictly following layout and style guidelines is something we care greatly about ;-) Switching completely to `ggplot` would allow the user to apply company or customer specific styling for all plots in a report in an easy way.
- wrt the webapp: it's a question of prioritizing. It would be interesting for sure, but apart from the data privacy issue, keep in mind that code is often a deliverable, i.e. something customers pay for. If there is some graphical interface it should be able to produce a working standalone script. I feel the additional models and the integration with reporting workflows are more important, if I had to chose what to prioritize.

Peter.

**Comment by giabaio** [comment]
I'm assuming you mean _"to use custom models in survHE"_ under a Bayesian approach? If so, basically there are very many possibilities. Some things can be already and very easily implemented. For example, `INLA` deals very easily with "structured" effects (eg random effects for repeated measures, or spatial/temporal structures). You would only need to modify the formula, eg `formula=inla.surv(time,censored)~fixed.effect1+fixed.effect2+f(random.effect,model="iid")` 
(there's more to this, of course, but this would be a good starting point). 

`INLA` can deal with other complicated models, but it needs some structural modification, which cannot be done externally (short of recoding the whole thing!). So the workflow is basically to have a detailed request and then the `INLA` development team can be involved (ie we can liaise with them and see if such models can be implemented in the `INLA` release and then used by `survHE`). 

As for HMC/`rstan`, things are both simpler and slightly more complex: on the one hand, you can basically code up *any* model you want, provided you're able to write a .stan model file and pass suitable data to it. So, in a sense, you don't *need* `survHE` if you are at _that_ level. But of course, we'd like you to simplify things and allow you to pass a user-defined model structure to `fit.models` for you to run. This is however a bit more complex from the point of view of `survHE`, because:
- you need to modify the `fit.model` function to allow to pick up the model file from a user-defined input.
- you need to compile the new model (unless it's been implemented in the main release of `survHE`); `fit.models` could take care of this (but this will increase the running time, at least for the first time that the model is run!). Of course, once a model has been suggested, we can include it in the main release, so that'd be nice and would allow continuous development of the `survHE` "library" of available models. 
- more importantly, we'd need to structure the rest of the package so that it can take care of user-defined models when running the downstream functions (eg `plot`, `make.surv`, etc). At the moment, all the available models are coded up so that `make.surv` knows what to do with them and then `print`, `plot` etc can also do the correct transformations so that tables and graphs work. If you have an arbitrary model, where the underlying scale for the parameters is unknown to start with, you'd need to have something like `flexsurv` structure to allow this mapping... Not impossible, but beyond `survHE`, at the moment...

Of course, if you have a model that you have in mind, it is possible to include it (and pre-compile it!) in `survHE`. That was the point I was making about including other possible models suggested by, eg, NICE guidelines. I think we already cover most and certainly what the average user would try (and, probably, most likely successfully use). 

As for reporting, I don't necessarily *want* to do the webapp. I think these things are good to bring more people to use the package and functionalities - but I agree with your general point, that they're not 100% priority...

Finally, the issue with `ggplot2`: the only part of `survHE` where `ggplot2` becomes relevant is when using the `rstan`-built in plots (eg `rstan::traceplot()`). That's because `rstan` uses `ggplot2` as the default (and, I think, only) graphical engine. As far as `survHE` is concerned, all graphs are produced using the `base` engine - mostly because I am more familiar with it and haven't got around learning `ggplot2` as well as to use it in a package. 

I know it's very efficient and I see your point about customising. On the other hand: 
1. If you are _that kind_ of user and know how to play with `ggplot2`, the output from `survHE` does allow you to do the graphs in any way you want. You can customise *everything* from the objects produced by `fit.models`, `make.surv` and `model.fit.plot`.
2. If you are _not_ that kind of user, then probably `base` is enough for you and you wouldn't be able to do much customisation... 

Nevertheless, I am not averse at all at including a `..., graph=c("base","ggplot2")` to the graphical functions of `survHE` so that the user can actually pick and choose which way they want - [Andrea](https://github.com/andbe) has actually done something like for `BCEA`

**Comment by lemna** [comment]
Thanks Gianluca,

This is exactly what I was looking for: guidance on how to add models to survHE. This might form the basis of a vignette. I'll probably submit PRs for ggplot implementations of the plot functions in the coming weeks, if that's ok with you.

Peter.

**Comment by giabaio** [comment]
Of course!



*Gianluca Baio*

*Reader in Statistics & Health Economics*
Department of Statistical Science
University College London
1-19 Torrington Place, London WC1E 6BT, UK
Telephone +44(0)20 7679 1248 (internal: 41248)
Fax +44 (0)20 7383 4703
Website: http://www.homepages.ucl.ac.uk/~ucakgba
<http://www.homepages.ucl.ac.uk/~ucakgba/>
Blog: http://gianlubaio.blogspot.co.uk

**Comment by giabaio** [comment]
Hi Peter and Andrea (I'm guessing you read this message). I am planning to write a proposal to do some more work on survHE. Are you interested in discussing this offline (ie not on the list)? Contact me directly if so!
Gianluca
