### ISSUE TITLE
covariate interaction terms

### ISSUE THREAD

**Issue by Geoff-Holmes** [giabaio/survHE#20]
Hi Gianluca

I'm wondering if it is possible to include interaction terms as is possible in the underlying flexsurv.
e.g.

> library(survHE)
> data(bc)
> bc$dummy<-round(runif(nrow(bc)))
> # This works fine
> mod1<-flexsurvspline(Surv(rectime, censrec) ~ group + dummy + group * dummy, data=bc)
> # This works fine
> mod2<-fit.models(Surv(rectime, censrec) ~ group + dummy, data=bc, distr="rps") 
> # This thows an error
> mod2<-fit.models(Surv(rectime, censrec) ~ group + dummy + group * dummy, data=bc, distr="rps")
Error in `[.data.frame`(data, , pmatch(covs, colnames(data))) : 
  undefined columns selected

**Comment by Geoff-Holmes** [comment]
Sorry the comments turned into large text!
I've realised I can (obviously!) just create a new column in the data for the interaction term.

**Comment by giabaio** [comment]
Hi Geoff,
No problems! And yes --- that is the way to deal with interactions. I think `flexsurvreg` may construct the "model matrix" (ie the matrix of covariates) automatically using the syntax `a:b` to mean interaction between `a` and `b`. `survHE` needs you to specify the new column `a*b` at the moment. I can see how quickly I can include the `a:b` notation --- shouldn't be too long (but possibly not super high priority?).
