### ISSUE TITLE
Development version installation issue under Windows (CXX14 not defined) [Solved]

### ISSUE THREAD

**Issue by andbe** [giabaio/survHE#25]
Installation of the development version via `devtools:install_github()` under Windows can fail with the following error message:
`Error in .shlib_internal(args) : C++14 standard requested but CXX14 is not defined`

A solution has been provided for the same issue [here](https://community.rstudio.com/t/error-in-shlib-internal-args-c-14-standard-requested-but-cxx14-is-not-defined/16819) which fixed the issue in my case:

```
dotR <- file.path(Sys.getenv("HOME"), ".R")
if (!file.exists(dotR)) 
  dir.create(dotR)
M <- file.path(dotR, "Makevars.win")
if (!file.exists(M)) 
  file.create(M)
cat("\nCXX14FLAGS=-O3 -Wno-unused-variable -Wno-unused-function",
    "CXX14 = $(BINPREF)g++ -m$(WIN) -std=c++1y",
    "CXX11FLAGS=-O3 -Wno-unused-variable -Wno-unused-function",
    file = M, sep = "\n", append = TRUE)
```

**Comment by giabaio** [comment]
Thanks, @andbe! This is a know issues with the new(er) versions of `rstan`, which (as I understand it!) uses a higher version of the `C++` compiler and so you need to tell `R` to also do that... Glad this workaround fixes the issue --- I'll also post on the `survHE` webpage, so we have another place to track this!

Thanks for your help! :-)
