### ISSUE TITLE
Stan Gompertz model - strictly positive shape parameter

### ISSUE THREAD

**Issue by andbe** [giabaio/survHE#28]
Hi Gianluca,
The current stan model specification for the Gompertz model restricts the shape parameter to be strictly positive. I would suggest relaxing this assumption to fit hazard functions decreasing with time.

Based on a couple of tests, it also appears that the current model sometimes gets stuck around small alpha values - when using a vague normal prior for alpha instead of a gamma, the model convergence seems to improve (on speed, Rhat, distance from flexsurvreg estimates).

Some edits would also be needed on `fit.models`. If this sounds reasonable I am happy to send a pull request.

**Comment by giabaio** [comment]
Perfect --- and sorry for being slow in replying. I've seen the pull request --- will check it out and then accept!
