### ISSUE TITLE
add.km in plot.survHE only works when the first element of the mods vector is specified

### ISSUE THREAD

**Issue by David-Andrew-Jones** [giabaio/survHE#35]
Hi Gianluca

Firstly, the package is fantastic so thank you very much.

I've come across a problem when plotting results from fit.models. It is only possibe to plot the KM curve when the first distribution is specified in the mods argument. For instance plot.survHE(data_fit, mods = c(1,5), add.km = TRUE) will plot the KM curve but plot.survHE(data_fit, mods = c(5), add.km = TRUE)  will not.

**Comment by giabaio** [comment]
Thank you! :-)

I think you're on the CRAN version of `survHE`, which did have this problem. I've fixed it on the development version, which you can get by using the following command
```
remotes::install_github("install_github("giabaio/survHE", ref="devel")
```
in fact, I *think* you can get the most updated code even without specifying `ref="devel"`. To be safe, use the code above, then you should be OK --- see example above
```
library(survHE)
m=fit.models(formula=Surv(recyrs,censrec)~group,data=bc,distr=c("exp","wei","gom"))
plot(m,mods=c(2,3))
```
which correctly produces the graph below.
![image](https://user-images.githubusercontent.com/8723145/104940832-309f7100-59aa-11eb-897e-4176e2d69e0d.png)
(ie the Exponential model, the first one in your list of models, is excluded).

I'm closing this issue now as I *think* it will be solved, but please do re-open if it still doesn't work!
