### ISSUE TITLE
surv.mean() is missing

### ISSUE THREAD

**Issue by lemna** [giabaio/survHE#4]
There is documentation for a ```surv.mean()``` function in surv.mean.Rd, but the actual function is missing in the code.

R CMD check output:
```
checking for code/documentation mismatches ... WARNING
Functions or methods with usage in documentation object 'surv.mean' but not in code:
  surv.mean
```

**Comment by giabaio** [comment]
Hi Peter,
This is kind of a typo --- the function `surv.mean()` doesn't exist because I decided to create a method `summary.survHE` that does what originally I thought it would do (ie compute the mean survival time, given a specific model).

So effectively you don't need any documentation for it.
