### ISSUE TITLE
Issue with survival time limits

### ISSUE THREAD

**Issue by rianmiller** [giabaio/survHE#43]
Hi there,

I am currently trying to replicate an OS curve from a clinical trial (https://www.nejm.org/doi/10.1056/nejmoa1709866) based on the algorithm from Guyot et al. 2012 and the survHE package.

Unfortunately I am expierencing a problem regarding the lower and upper values for the number at risk file, which is later used for the digitize function:
_"Error in find_interval_limits(start_time = c(0, 2, 4, 6, 8, 10, 12, 14,  : 
  Intervals must span all survival times. Later interval missing."_

This is my code so far:
library("survHE")

MD_OS_Data <-read.csv("MD-KMC-OS-2.csv", header= TRUE, sep=";")
head(MD_OS_Data)

find_interval_limits <- function(start_time,
                                 surv_time){
  
  if (max(surv_time) > max(start_time))
    stop("Intervals must span all survival times. Later interval missing.")
  
  interval <- 1
  end_time <- start_time[2]
  upper <- NULL
  
  for (i in seq_along(surv_time)){
    
    if (surv_time[i] >= end_time) {
      
      upper[interval] <- i - 1 
      interval <- interval + 1
      end_time <- start_time[interval + 1]
    } 
  }
  
  cbind(lower = c(1, upper + 1),
        upper = c(upper, length(surv_time)))
}

interval_limits <-
  find_interval_limits(start_time = c(0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22),
                       surv_time = MD_OS_Data$Time)
  
MD_OS_atrisk <- read.csv("MD-nrisk-OS.csv", header=TRUE, sep=";")
MD_OS_atrisk[,c("lower","upper")] <- interval_limits
head(MD_OS_atrisk)

Hope anyone can help me, I also attached my input files.
P.S. I am working with R version 4.1.1

Thanks! :)

[MD-KMC-OS-2.csv](https://github.com/giabaio/survHE/files/7554159/MD-KMC-OS-2.csv)
[MD-nrisk-OS.csv](https://github.com/giabaio/survHE/files/7554160/MD-nrisk-OS.csv)

**Comment by giabaio** [comment]
If I load the data you have linked, I see two problems:
1. The variables are actually characters
2. What would be numerical values use commas to separate decimals.

You need to ensure that the data are numeric and that use use "." as separator for decimals. Can you try fixing this and see if the problem persists?

**Comment by rianmiller** [comment]
Hi Gianluca,

sorry for the late reply. I checked both .csv and changed the separators. Seemed like there were some data inconsistencies too but after changed that everything worked fine.

Thanks for the help!
