### ISSUE TITLE
Error in rep(t.S[j], d[j]) : invalid 'times' argument

### ISSUE THREAD

**Issue by lexieD** [giabaio/survHE#47]
I get this error: 
Error in rep(t.S[j], d[j]) : invalid 'times' argument

HERE IS THE COED I USE
surv_inp<-"survrego.txt"
nrisk_inp<-"nriskrego.txt"
Km_out<-"KMrego.txt"
ipd_out<-"IPDrego.txt"
digitise(surv_inp,nrisk_inp,km_output ="KMrego.txt",ipd_output = "IPDrego.txt")

survrego
K	Tk	S
1	0.00	100.00
2	0.29	99.98
3	0.39	99.90
4	0.48	99.74
5	0.57	99.18
6	0.67	99.02
7	0.76	98.85
8	0.86	98.63
9	0.95	98.51
10	1.05	98.47
11	1.64	98.31
12	1.73	97.81
13	1.82	97.51
14	1.92	97.43
15	2.01	97.23
16	2.09	96.60
17	2.18	96.30
18	2.27	95.98
19	2.35	95.24
20	2.44	95.08
21	2.53	94.90
22	2.63	94.44
23	2.72	93.99
24	2.81	93.65
25	2.88	92.79
26	2.95	91.78
27	3.03	90.94
28	3.11	90.60
29	3.19	89.94
30	3.28	89.27
31	3.36	88.39
32	3.40	87.10
33	3.58	86.18
34	3.67	85.66
35	3.69	85.30
36	3.96	85.09
37	4.05	84.63
38	4.14	84.11
39	4.22	83.37
40	4.28	82.36
41	4.33	81.26
42	4.40	80.39
43	4.48	79.79
44	4.58	79.45
45	4.68	79.25
46	4.68	78.89
47	4.74	77.84
48	4.93	77.12
49	4.99	76.05
50	5.03	74.65
51	5.08	73.48
52	5.18	73.30
53	5.20	73.00
54	5.22	71.62
55	5.31	70.85
56	5.34	69.53
57	5.44	69.49
58	5.53	68.84
59	5.61	68.22
60	5.70	67.86
61	5.79	67.42
62	5.88	66.67
63	5.94	65.61
64	5.99	64.36
65	5.99	63.18
66	6.01	62.96
67	6.19	62.54
68	6.27	61.93
69	6.34	60.87
70	6.41	59.96
71	6.50	59.52
72	6.59	59.24
73	6.68	58.70
74	6.77	58.22
75	6.87	57.98
76	6.97	57.89
77	7.06	57.81
78	7.16	57.59
79	7.26	57.15
80	7.34	56.47
81	7.42	55.60
82	7.50	54.76
83	7.58	54.20
84	7.68	54.00
85	7.78	53.98
86	8.07	53.86
87	8.15	53.23
88	8.24	52.41
89	8.31	51.53
90	8.39	50.76
91	8.48	50.26
92	8.58	50.00
93	8.67	49.70
94	8.76	49.20
95	8.84	48.47
96	8.92	47.61
97	8.98	46.48
98	9.03	45.18
99	9.08	44.17
100	9.18	43.95
101	9.27	43.83
102	9.35	43.09
103	9.54	42.41
104	9.59	41.06
105	9.69	40.78
106	9.77	40.10
107	9.82	39.92
108	9.84	39.09
109	10.17	38.99
110	10.56	38.71
111	10.64	38.25
112	10.73	38.15
113	10.83	38.13
114	11.02	38.09
115	11.12	37.93
116	11.70	37.08
117	11.76	36.00
118	11.95	35.94
119	12.04	35.36
120	12.13	34.83
121	12.23	34.35
122	12.32	33.87
123	12.41	33.29
124	12.50	32.80
125	12.59	32.54
126	12.69	32.46
127	12.79	32.44
128	13.18	32.26
129	13.27	31.74
130	13.35	31.26
131	13.44	30.70
132	13.52	30.19
133	13.62	30.03
134	13.93	29.09
135	13.98	27.86
136	14.07	27.34
137	14.46	27.32
138	14.54	26.60
139	14.62	25.65
140	14.69	24.81
141	14.74	24.61
142	14.78	23.32
143	14.83	22.30
144	14.83	22.10
145	14.97	21.86
146	15.32	21.84
147	16.33	21.09
148	16.35	11.03
149	16.40	10.12
150	16.49	9.86

nriskrego
i	Triski	Lower	Upper	Nrisk
1	0	1	14	136
2	2	15	36	131
3	4	37	65	113
4	6	66	85	88
5	8	86	108	72
6	10	109	118	52
7	12	119	135	42
8	14	136	146	24
9	16	147	150	4

**Comment by giabaio** [comment]
@lexieD did you manage to solve this? I think this is the same as #41
