### ISSUE TITLE
Error: incompatible types (from closure to double)

### ISSUE THREAD

**Issue by Ysann3** [giabaio/survHE#57]
Dear Giabaio, 

After preparing my data for the digitise function (I digitized my KM curve with PlotDigitzer)
I get the following error when running the function:

```
digitise(surv_inp = "Cilta_data.txt",
+                      nrisk_inp = "Cilta_atrisk.txt")
Error in last.i[(i + 1)] <- last : 
  incompatible types (from closure to double) in subassignment type fix
```
This is a preview of the txt files, I have attached them as well ->[Cilta_atrisk.txt](https://github.com/giabaio/survHE/files/11575674/Cilta_atrisk.txt)
[Cilta_data.txt](https://github.com/giabaio/survHE/files/11575675/Cilta_data.txt)

Cilta_data.txt:

"k" 	"Time" 			"Survival"
1 	0 			99.8217445079071
2 	0.985139457519403 	100.178253792138
3 	0.869242258232916 	98.3957226705681
4 	1.5066856966981 	98.7522285548914
5 	1.39078849741161 	97.5044571097828
6 	1.97028333623356 	97.3262050175982

Cilta_atrisk.txt:
"time" "nrisk" "interval" "lower" "upper"
3 96 1 1 8
6 91 2 9 19
9 88 3 20 27
12 85 4 28 31
15 81 5 32 40
18 79 6 41 46

I have googled the error, but being a relative beginner in coding, I am not sure how I should handle the closure to double error. 
Do you have any pointers?

Many thanks!
Ysanne

**Comment by giabaio** [comment]
I think there's a few things wrong with the digitised data. Firstly, you don't have monotonic times in the actual data so you start with a survival value of less than 100 and then you go up to a value over 100. Secondly, I think the survival column should be proportions (so numbers between 0 and 1). Also, the original example for the `at risk` file has the column in a different order (interval, time, lower, upper, nrisk).

I wonder whether these make a difference...

**Comment by Ysann3** [comment]
Perfect, it now works with the survival data as proportions and monotonic data! Thank you for the quick reply.
