### ISSUE TITLE
Error to plot survival curves for the models fitted using fit.models

### ISSUE THREAD

**Issue by GMarasco** [giabaio/survHE#59]
Hello Gianluca.

I am having some problems when trying to plot my survival curves for the models fitted using fit.models.

I got all the results I needed using fit.models but when I try to plot my survival curves I get the error: Error in terms.formula(tmp, simplify = TRUE)

What am I doing wrong?

Thanks!

**Comment by giabaio** [comment]
It's hard to debug with this little information. Can you make a reproducible example so I can have a look?

**Comment by GMarasco** [comment]
Thanks for your support! We solved it out.

The problem was related to the code I was using in fit.models.

Let me explain a little bit more with some example.

The code I was using:
expon = fit.models(formula=Surv(test_ipd [,1],test_ipd [,2])~1,data=test_ipd,distr="exp",method="mle")

The code after update:
expon = fit.models(formula=Surv(time,event)~1,data=test_ipd,distr="exp",method="mle")

test_ipd was obtained using digitise function.

I am new to R, sorry for my dumbness.

Best regards!
